// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function adjacent_coord(direction) {
  switch (direction) {
    case 0 : 
        return /* tuple */[
                0,
                -1
              ];
    case 1 : 
        return /* tuple */[
                0,
                1
              ];
    case 2 : 
        return /* tuple */[
                1,
                0
              ];
    case 3 : 
        return /* tuple */[
                -1,
                0
              ];
    
  }
}

var adjacent = /* :: */[
  /* Up */0,
  /* :: */[
    /* Down */1,
    /* :: */[
      /* Right */2,
      /* :: */[
        /* Left */3,
        /* [] */0
      ]
    ]
  ]
];

exports.adjacent       = adjacent;
exports.adjacent_coord = adjacent_coord;
/* No side effect */
